In [8]:
import numpy as np
import matplotlib.pyplot as plt

In [18]:
# doklejenie wartości
ar = np.array([1,2,-3,6,7,-10,88,43,-98,17,39,45])
ar

array([  1,   2,  -3,   6,   7, -10,  88,  43, -98,  17,  39,  45])

In [19]:
ar2 = np.array([4,5,9,10,23,-14,55,13])

In [24]:
wektory = np.concatenate((ar, ar2))

In [25]:
wektory

array([  1,   2,  -3,   6,   7, -10,  88,  43, -98,  17,  39,  45,   4,
         5,   9,  10,  23, -14,  55,  13])

In [39]:
#znajdz index dla wartości 9 - użyj odpowiedniej funkcji
wektory.tolist().index(9)


14

In [45]:
#znajdź indeksy dla wartości mniejszych od zera
wektory < 0

array([False, False,  True, False, False,  True, False, False,  True,
       False, False, False, False, False, False, False, False,  True,
       False, False], dtype=bool)

In [46]:
for index, value in enumerate(wektory):
    if value < 0:
        print(index)

2
5
8
17


In [48]:
#wyświetl wartości mniejsze od zera
for value in wektory:
    if value < 0:
        print(value)

-3
-10
-98
-14


In [56]:
#policz średnią, zaokrąglij do jednego miejsca po przecinku
np.mean(wektory)

12.1

In [64]:
#stwórz zmienną ar_abs, wektor wartości bezwględnych z wektora ar
ar_abs = max(np.absolute(ar))

In [65]:
ar_abs

98

In [70]:
#stwórz zmienną ar_p, wektor pierwiastków trzeciego stopnia z wektora ar_abs
ar_p = np.cbrt(ar_abs)

In [71]:
ar_p

4.6104362920584467

In [90]:
format(ar_p, '.2f')

'4.61'

In [91]:
#zsumuj zaokrąglony wektor ar_p i podnieś go do kwadratu
np.sum(ar_p)
ar_sq = np.square(ar_p) 

In [92]:
ar_p

4.6104362920584467

In [93]:
type(ar_sq)

numpy.float64

In [94]:
#zmienną nazwij ar_sq, zmień typ tej zmiennej na liczbę całkowitą
ar_sq.astype(int)

21